Pact Station
The-Weasel-Flockmind/Weasel-Station pull request #46
Opened 2024-10-30 00:37 UTC by LukeZurg22

## About the PR
Added new station.

## Why / Balance
Because it's a new station that's been in development for a while now. (See Weasel Discord -> Pact Station thread)

## Technical details
It's a map + prototype.

## Media
No ingame changes.

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**
- added: pact station, courtesy of Union J

2024-10-30 00:44 UTC, GroggleG requested changes
You changed our sln for some reason, revert that and Ill run the checks.

2024-10-30 01:40 UTC, LukeZurg22 commented
Note: RTG's in bulk not included. They were there for testing purposes.
For the **.sln**, simply merge and reject the **.sln** changes.

2024-10-30 02:17 UTC, GroggleG commented
> You changed our sln for some reason, revert that and Ill run the checks.

Your .sln is STILL different

2024-10-30 02:27 UTC, LukeZurg22 commented
> > You changed our sln for some reason, revert that and Ill run the checks.
> 
> Your .sln is STILL different

Third time: I STILL do not know how to remove the .sln difference from this commit! I would highly advise just discarding the changes to the .sln on merge!

2024-10-30 14:26 UTC, GroggleG commented on Content.Benchmarks/MapLoadBenchmark.cs
Uoui was also added, the // is just so that if there are merge conflicts

2024-10-30 14:29 UTC, GroggleG commented
I may or may not forcemap this in the future, letting the checks run.

2024-10-30 15:05 UTC, LukeZurg22 commented on SpaceStation14.sln
Again, I have no idea why it pushed the **.sln**. I did a double take at the changes panel and didn't even see the **.sln** changes _there._ Discard the **.sln** modifications on merge if needed.

2024-10-30 15:20 UTC, LukeZurg22 commented
> I may or may not forcemap this in the future, letting the checks run.

I ran this locally on my machine with the Weasel fork. Map loaded perfectly without any problems or errors. I'd wager the checks are giving a false positive. Why -I cannot say.

2024-11-02 06:17 UTC, GroggleG commented
yeah the build test is almost done, this sh-

2024-11-02 06:17 UTC, GroggleG commented
what

2024-11-02 06:19 UTC, Froxxin commented
![Screenshot 2024-11-02 021843](https://github.com/user-attachments/assets/4c41296f-5bdc-4051-9f2a-c9b7a577fc81)

2024-11-02 06:21 UTC, Froxxin commented
Sorry didn't mean to close it lol

2024-11-02 06:42 UTC, LukeZurg22 commented
> ![Screenshot 2024-11-02 021843](https://private-user-images.githubusercontent.com/162259293/382452577-4c41296f-5bdc-4051-9f2a-c9b7a577fc81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjk5NTcsIm5iZiI6MTczMDUyOTY1NywicGF0aCI6Ii8xNjIyNTkyOTMvMzgyNDUyNTc3LTRjNDEyOTZmLTViZGMtNDA1MS05ZjJhLWM5YjdhNTc3ZmM4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNjQwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjgxMmQxNzFiNTk3YWQ4N2ZiM2FmN2U2ZTg3NTkxMzczY2ZlMGU5Yzc4YWExZjg1MzRiYWE4ZDM1MzE2Mjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4QlxTIqaf7u5l7qmQyv92dsClVOqH8Pj7ThusNMYY0w)

Desperately trying to appease the envelop-hating deity in the machine. All mere mentions of the envelop are gone from the file, yet it craves its memory to be bleached from the threads of time.

2024-11-02 18:44 UTC, merged